###
GET http://localhost:3000/api/v1/receptionist/
Content-Type: application/json

{
    "regNo": "S13/07838/22"
}

###
POST http://localhost:3000/api/v1/receptionist


###
PATCH  http://localhost:3000/api/v1/receptionist

###
DELETE http://localhost:3000/api/v1/receptionist